### ISSUE TITLE
Problem with setup script

### ISSUE THREAD

**Issue by Ganyme-d** [TheLartians/PyPropagate#41]
I tried installing with `pip install pypropagate` which leads to the error `'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
`.

I am using Linux Mint 19 with the newst version of Anaconda, pip version 18.0 and setuptools version 40.4.1

**Comment by TheLartians** [comment]
I updated the script und reuploaded to PyPi. Can you try again?

**Comment by Ganyme-d** [comment]
Thanks, I think that fixed it!

**Comment by TheLartians** [comment]
Great! Let me know if you encounter other issues.
